config/routes.rb
Rails.application.routes.draw do
  root "messages#index"
  resources :messages, only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  has_many_attached :image
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update]

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def message_params
    params.require(:message).permit(:content, images: [])
  end

  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniImageApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with model: @message, id: 'new_message', local: true do |f| %>
  <%= f.text_field :content, placeholder: 'type a message' %>
  <%= f.file_field :images, name:'message[imaegs][]',id: 'message_image' %> 
  <%= f.submit '送信' %>
  <div id="image-list">
    <% @message.images.each do |image| %>
      <%= image_tag image, class: 'images' %>
    <% end %>
  </div>

  <%# <%= image_tag @message.image, id: 'image' if @message.image.present? %>  
<% end %>

app/views/messages/edit.html.erb
<h3>編集</h3>
<%= render partial: 'form' %>

app/views/messages/index.html.erb
<h3>トップページ</h3>
<h3><%= link_to '新規投稿', new_message_path%></h3>
<% @messages.each do |message| %>
  <%= message.content%>
    <div class="messages">
    <% message.images.each do |image| %>
      <%= image_tag image, class:'images' %>
    <% end %>
  </div>
  <%= link_to '編集', edit_message_path(message.id)%>
<% end %>

app/views/messages/new.html.erb
<h3>新規投稿</h3>
<%= render partial: "form" %>